<a href="https://colab.research.google.com/github/ishikaagarwal055/Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

Day10

In [ ]:
#reshape array 2d
import numpy as np
arr = np.arange(12) #12 =>3*4 ||4*3
up_arr = np.reshape(arr,(3,4)) # 3->row ||4 ->cols
print(up_arr)

#example 2d
import numpy as np
arr = np.arange(18)
up_arr = np.reshape(arr,(9*2))
print(up_arr)

#example 3d
import numpy as np
arr = np.arange(18)
up_arr = np.reshape(arr,(3*3*2))
print(up_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [ ]:
#lattin
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)
up_arr = arr.flatten()
up_arr[0] = 100
print(up_arr)
print(arr)

#example 3d
import numpy as np
arr = np.arange(18).reshape(3,3,2)
print(arr)
up_arr = arr.flatten()
up_arr[0] = 100
print(up_arr)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[100   1   2   3   4   5   6   7   8   9  10  11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [ ]:
#ravel -> works on original array
#example 2d
import numpy as np
arr = np.arange(12).reshape(6,2)
print(arr)
up_arr = arr.ravel()
up_arr[0] = 100
print(up_arr)
print(arr)

#example 3d
import numpy as np
arr = np.arange(18).reshape(3,3,2)
print(arr)
up_arr = arr.ravel()
up_arr[0] = 100
print(up_arr)
print(arr)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17]
[[[100   1]
  [  2   3]
  [  4   5]]

 [[  6   7]
  [  8   9]
  [ 10  11]]

 [[ 12  13]
  [ 14  15]
  [ 16  17]]]


Transpose

In [ ]:
#transpose -> rows convert into cols || cols convert into rows
#2d
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)
up_arr = arr.transpose()
print(up_arr)

#3d
import numpy as np
arr = np.arange(18).reshape(3,3,2)
print(arr)
up_arr = arr.transpose()
print(up_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
[[[ 0  6 12]
  [ 2  8 14]
  [ 4 10 16]]

 [[ 1  7 13]
  [ 3  9 15]
  [ 5 11 17]]]


Slicing operation

In [ ]:
#slicing for 1d
# import numpy as np
# arr = np.arange(11)
# print(arr)
# up_arr = arr[:3]
# print(up_arr)

#2d
# import numpy as np
# arr = np.arange(16).reshape(8,2)
# print(arr)
# up_arr = arr[:,-1]
# print(up_arr)
# print(arr)

#3d
import numpy as np
arr = np.arange(24).reshape(3,2,4)
print(arr)
up_arr = arr[0,0,0]
print(up_arr)
up_arr = arr[-1,-1,-1]
print(up_arr)
print(arr[0,0,0],arr[2,1,3])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
0
23
0 23


Looping with numpy
  1. while loop
  2. for loop

In [ ]:
from re import I
#while loop
#1d
# import numpy as np
# arr = np.arange(12)
# i = 0
# while i<len(arr):
#   print(arr[i], end="")
#   i+=1

#2d
import numpy as np
arr = np.arange(12).reshape(3,4)
i = 0
len_i = len(arr)
len_j = len(arr[i])
while i<3:
  j = 0
  while j< len_j:
    print(arr[i][j], end="")
    j+=1
  i+=1
print(type(arr))

#3d
# import numpy as np
# arr = np.arange(27).reshape(3,3,3)
# i = 0
# while i< len(arr):
#   j = 0
#   while j< len(arr[i]):
#     k = 0
#     while k< len(arr[i][j]):
#       print(arr[i][j][k], end="")
#       k+=1
#     j+=1
#   i+=1
# print(type(arr))


01234567891011<class 'numpy.ndarray'>


In [ ]:
#for loop
#1d
# import numpy as np
# arr = np.arange(12)
# for i in range(len(arr)):
#   print(arr[i], end="")

#2d
# import numpy as np
# arr = np.arange(12).reshape(3,4)
# for i in range(len(arr)):
#   for j in range(len(arr[i])):
#     print(arr[i][j], end="")

#3d
import numpy as np
arr = np.arange(18).reshape(3,3,2)
for i in range(len(arr)):
  for j in range(len(arr[i])):
    for k in range(len(arr[i][j])):
      print(arr[i][j][k], end="")

01234567891011121314151617

In [ ]:
import numpy as np

# Data Structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("1. Complete Dataset:")
print(sales_data)

print("\n2. Shape of Array:")
print(sales_data.shape)

print("\n3. Number of Dimensions:")
print(sales_data.ndim)

print("\n4. Total Number of Elements:")
print(sales_data.size)

print("\n5. Restaurant IDs:")
print(sales_data[:, 0])

print("\n6. 2021 Sales Data:")
print(sales_data[:, 1])

print("\n7. 2024 Sales Data:")
print(sales_data[:, 4])

print("\n8. Maximum Sales Value:")
print(np.max(sales_data[:, 1:]))

print("\n9. Minimum Sales Value:")
print(np.min(sales_data[:, 1:]))

print("\n10. Total Sales in 2021:")
print(np.sum(sales_data[:, 1]))

print("\n11. Average Sales in 2024:")
print(np.mean(sales_data[:, 4]))

print("\n12. Total Sales of Each Restaurant (2021-2024):")
print(np.sum(sales_data[:, 1:], axis=1))

print("\n13. Average Sales of Each Restaurant:")
print(np.mean(sales_data[:, 1:], axis=1))

print("\n14. Restaurant with Highest 2024 Sales:")
highest_2024_index = np.argmax(sales_data[:, 4])
print(sales_data[highest_2024_index])

print("\n15. Year-wise Total Sales (2021-2024):")
print(np.sum(sales_data[:, 1:], axis=0))

print("\n16. Year-wise Average Sales (2021-2024):")
print(np.mean(sales_data[:, 1:], axis=0))

print("\n17. Add New Column for 2025 Sales:")
sales_2025 = np.array([[280000],
                       [210000],
                       [330000],
                       [300000],
                       [250000]])

updated_data = np.hstack((sales_data, sales_2025))
print(updated_data)

print("\n18. Delete Restaurant ID 3 Data:")
deleted_data = np.delete(sales_data, 2, axis=0)
print(deleted_data)

print("\n19. Growth from 2023 to 2024:")
growth = sales_data[:, 4] - sales_data[:, 3]
print(growth)

print("\n20. Restaurant with Maximum Total Sales:")
total_sales = np.sum(sales_data[:, 1:], axis=1)
max_index = np.argmax(total_sales)

print("Restaurant ID:", sales_data[max_index, 0])
print("Total Sales:", total_sales[max_index])

In [ ]:
#sort
#1d
# import numpy as np
# arr = np.array([10,40,30,60,90,7,5])
# print(arr)
# arr_s = np.sort(arr)
# print(arr_s)

#2d
# axis = 0 -> cols
# axis = 1 -> rows
# import numpy as np
# arr = np.array([[5,60,20],[40,90,4]])
# print(arr)
# arr_s = np.sort(arr, axis=0)
# print(arr_s)

# example of sort for 2d
# axis = 0 -> cols
# axis = 1 ->rows
# import numpy as np
# arr = np.array([[50,20,8],[60,30,4]])
# print(arr)
# arr_s = np.sort(arr, axis=1)
# print(arr_s)

#by default sorting ->ascending|descending
import numpy as np
arr = np.array([10,40,30,60,90,7,5])
print(arr)
arr_s = np.sort(arr)
print(arr_s)
arr_des = np.sort(arr)[::-1]
print(arr_des)


[10 40 30 60 90  7  5]
[ 5  7 10 30 40 60 90]
[90 60 40 30 10  7  5]


Filter

In [ ]:
#1d
import numpy as np
arr = np.array([10,20,40,6,3,4,2])
print(arr)
arr_f = arr[arr<40]
print(arr_f)

#example
import numpy as np
arr = np.array([20,40,5,3,96,51])
print(arr)
arr_f = arr[arr<20]
print(arr_f)

[10 20 40  6  3  4  2]
[10 20  6  3  4  2]
[20 40  5  3 96 51]
[5 3]


Fancy indexing vs np.where()
  1.array(list)
  2.array([0,1,2])
  3.np.where(expression) ->ternary opr
  4.np.where(array>2)
  5.np.where(array>2,array*2,array)
  6.np.where(array>2,"true","false")



In [ ]:
import numpy as np
arr = np.array([10,20,3,4,90,100])
print(arr)
arr_f = arr[[0,2]] # 0 index value, 2 index value
print(arr_f)

import numpy as np
arr=np.array([10,20,3,4,90,100])
print(arr)

arr_f = arr[[0,2,5]]
print(arr_f)

[ 10  20   3   4  90 100]
[10  3]
[ 10  20   3   4  90 100]
[ 10   3 100]


In [ ]:
#np.where
import numpy as np
#1d
arr = np.array([10,3,4,80,30,40,9])
print(arr)
arr_w = np.where(arr>40,"True","False")
print(arr_w)

#example
arr = np.array([10,3,4,80,30,40,9])
print(arr)
arr_w = np.where(arr>40,arr+2,arr-2) # condition : true :false
#if (arr>40)
# arr+2
#else
# arr-2
print(arr_w)

#2d
arr = np.array([[10,2,34],[32,54,6]])
print(arr)
arr_w = np.where(arr>20,"True","False")
print(arr_w)

[10  3  4 80 30 40  9]
['False' 'False' 'False' 'True' 'False' 'False' 'False']
[10  3  4 80 30 40  9]
[ 8  1  2 82 28 38  7]
[[10  2 34]
 [32 54  6]]
[['False' 'False' 'True']
 ['True' 'True' 'False']]


In [ ]:
#concatenate
#1d
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr_con = np.concatenate((arr1,arr2))
print(arr_con)

#manually
arr1_arr2_new = arr1+arr2
print(arr1_arr2_new)

#2d
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr_con = np.concatenate((arr1,arr2), axis=1)
print(arr_con)

#3d
import numpy as np
arr1 = np.array([[[2,6,4],[3,7,5],[25,63,23]]])
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr_con = np.concatenate((arr1,arr2))
print(arr_con)

[1 2 3 4 5 6]
[5 7 9]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[ 2  6  4]
  [ 3  7  5]
  [25 63 23]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]


In [ ]:
# import numpy as np
# arr = np.array([10,20,30,40,3])
# print(arr)
# arr_m = np.median(arr)
# print(arr_m)

# import numpy as np
# arr = np.array([10,20,2,34,1])
# print(arr)
# arr_min = np.min(arr)
# print(arr_min)

# import numpy as np
# arr = np.array([10,20,34,54,21])
# print(arr)
# arr_max = np.max(arr)
# print(arr_max)

#statistical function
import numpy as np
arr = np.array([10,20,2,34,43])
print(arr)
arr_mean = np.mean(arr)
print(arr_mean)
arr_std = np.std(arr)
print(arr_std)
arr_var = np.var(arr)
print(arr_var)

import numpy as np
arr = np.array([10,20,23,32,43])
print(arr)


[10 20  2 34 43]
21.8
15.051910177781423
226.56
[10 20 23 32 43]
